[package]
name = "amas-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
floem.workspace = true
